name: NanoCraftDiscordLinked
version: '${project.version}'
main: me.motasim.nanocraftdiscordlinked.NanoCraftDiscordLinked
api-version: '1.20'
commands:
  link:
    description: Link your discord account with your minecraft account for rewards.
    usage: /<command>